name = "PPredict"
uuid = "831750d9-4222-4fb2-bbc0-db5fbf7dd2d0"
authors = ["Steve Frank <saf@stevefrank.org>"]
version = "0.1.0"

[deps]
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJParticleSwarmOptimization = "17a086e9-ed03-4f30-ab88-8b63f0f6126c"
MLJScikitLearnInterface = "5ae90465-5518-4432-b9d2-8a1def2f0cab"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
ReservoirComputing = "7c2d2b1e-3dd4-11ea-355a-8f6a8116e294"
ScikitLearn = "3646fa90-6ef7-5e7e-9f22-8aca16db6324"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
